# extracted real project data (kept verbatim)
PROJECTS = [
    dict(
        slug="jurassic-quest", name="Jurassic Quest", url="https://jurassicquest.com",
        cat="Growth &amp; Platform", tag="Growth &amp; Platform", shot="jurassicquest.jpg",
        metric_n="3,500", metric_l="ticket sales recovered",
        blurb="North America&rsquo;s largest touring dinosaur experience &mdash; where I built an abandoned-cart recovery platform on their Universe.com ticketing that won back 3,500 sales.",
        brief="Jurassic Quest sells event tickets through Universe.com. Like every ticketing store, a large share of buyers add tickets and leave before paying &mdash; and there was no built-in way to bring them back.",
        work=[
            "Built a shopping-cart recovery platform on top of their Universe.com ticketing store to catch abandoned checkouts.",
            "Automated recovery outreach that reconnected drop-off buyers with the exact event they were about to book.",
            "Recovered <b>3,500 ticket sales</b> that would otherwise have been lost.",
        ],
        stack=["Universe.com", "Cart-recovery automation", "Email"],
    ),
    dict(
        slug="dosey-doe", name="Dosey Doe", url="https://doseydoe.com",
        cat="Social &amp; Events", tag="Social &amp; Events", shot="doseydoe.jpg",
        metric_n="600+", metric_l="events promoted",
        blurb="A legendary live-music hall and restaurant in The Woodlands, TX &mdash; where I ran Facebook Events and social media across 600+ shows.",
        brief="Dosey Doe runs a packed calendar of live music, and every show has to fill the room. That work starts on social &mdash; event pages, promotion, and audience engagement, week after week.",
        work=[
            "Managed Facebook Events and social-media promotion for <b>600+</b> live-music events.",
            "Built and ran the event pages that drove ticket awareness and turnout, show after show.",
            "Kept the social calendar full across a relentless live-event schedule.",
        ],
        stack=["Facebook Events", "Meta Business", "Social Media"],
    ),
    dict(
        slug="consent-resolve", name="Consent Resolve", url="https://consentresolve.com",
        cat="Co-founder &middot; SaaS", tag="SaaS &middot; my own company", shot="consentresolve.jpg",
        role="Co-founder &amp; CMO",
        blurb="The privacy-first visitor-ID platform I co-founded for home-service contractors &mdash; identify site visitors by name and email, only with consent, at a flat $7 a lead. I lead marketing and built the site.",
        brief="Consent Resolve is my company &mdash; I co-founded it and run marketing as CMO. It had to sell a genuinely new, compliance-first idea (warm-inbound visitor identification) while staying on the right side of TCPA, CIPA and the Texas TDPSA. Trustworthy, never creepy.",
        work=[
            "Designed and built the full marketing site (Astro &rarr; Cloudflare) around a locked &ldquo;warm-inbound&rdquo; story: identify a consented email, feed the client&rsquo;s own retargeting, let the homeowner come back and call.",
            "Reframed the compliance narrative around real U.S. contractor risk &mdash; TCPA, CIPA, and the Texas TDPSA &mdash; instead of generic GDPR boilerplate.",
            "Built an interactive product demo (register &rarr; visit &rarr; consent) that emails the prospect their own &ldquo;recovered lead&rdquo; so they feel the product work.",
            "Wired a consent-management autoblocker and mirrored every demo into an in-house CRM.",
        ],
        stack=["Astro", "Cloudflare Pages/Workers", "Resend", "D1 &amp; KV"],
    ),
    dict(
        slug="deuces-wild-poker", name="Deuces Wild Poker Club", url="https://deuceswildpokertx.com",
        cat="Website &amp; Local SEO", tag="Website &amp; SEO", shot="deuceswildpoker.jpg",
        blurb="A private poker club in Huntsville, TX — rebuilt from a page builder into a fast, self-owned site engineered to be found and to fill seats.",
        brief="Deuces Wild was locked inside a page builder with organic search as its only real channel. It needed a site it owned, built to rank in a market full of bigger-city competitors.",
        work=[
            "Replaced a Durable page-builder site with a hand-built, conversion-first static site on Cloudflare Workers &mdash; no builder, fully owned.",
            "Shipped 40+ pages including 20 local &ldquo;poker near {town}&rdquo; pages with real geographic hooks and schema.",
            "Built the SEO/AEO layer &mdash; llms.txt, structured data, a 301 map, and explicit AI-crawler access so answer engines can cite it.",
            "Stood up an autonomous B2B events-outreach engine (Resend, 3-touch sequences) and an SMS opt-in that writes straight to the owner&rsquo;s spreadsheet.",
        ],
        stack=["Cloudflare Workers", "D1", "KV", "Resend", "GA4"],
    ),
    dict(
        slug="booked-job", name="Booked Job", url="https://booked-job.com",
        cat="Brand &amp; AI Automation", tag="AI &amp; Automation", shot="bookedjob.jpg",
        blurb="An autonomous content brand for service pros — a marketing machine that writes, renders, voices, and posts itself across every channel.",
        brief="Booked Job is a proving ground: can an entire content brand run itself? The goal was a marketing engine that produces and publishes real, fact-checked content with no one at the keyboard.",
        work=[
            "Built a fully autonomous multi-channel publishing engine (GitHub Actions + a Cloudflare cron Worker) posting to Facebook, Instagram, YouTube, Mastodon, Pinterest and LinkedIn &mdash; no laptop in the loop.",
            "Engineered a Remotion video engine that renders brand-locked vertical reels and long-form video, voiced with ElevenLabs over generated art.",
            "Ran an audio podcast pipeline that publishes an RSS feed live on Spotify.",
            "Grounded every statistic in a sourced, adversarially fact-checked dataset &mdash; no invented numbers.",
        ],
        stack=["Cloudflare Workers", "GitHub Actions", "Remotion", "ElevenLabs", "Buffer", "Resend"],
    ),
    dict(
        slug="br-productions", name="B&amp;R Productions", url="https://bandrproduction.com",
        cat="Website Migration", tag="Website &amp; Migration", shot="bandrproduction.jpg",
        blurb="A Texas CNC machine shop, in business since 1994 — moved off a page builder onto a fast, self-owned site.",
        brief="B&amp;R had decades of reputation but a site trapped in a page builder, with broken images and a dead contact form. They needed to own their site and have it actually work.",
        work=[
            "Migrated the shop off Durable to a static, self-owned site on Cloudflare Workers.",
            "Mirrored 32 pages &mdash; capabilities, industries, and 20 service-area pages &mdash; from a sitemap-restricted crawler.",
            "Solved the framework&rsquo;s image-optimizer hydration bug by self-hosting all 212 images behind a runtime shim.",
            "Rebuilt a working quote form on a Cloudflare Worker with Resend, removed the third-party chat widget, and preserved analytics.",
        ],
        stack=["Cloudflare Workers", "Resend", "Python pipeline", "GTM"],
    ),
    dict(
        slug="lakeside-ink-threadz", name="Lakeside Ink &amp; Threadz", url="https://lakesidethreadz.com",
        cat="Website Migration", tag="Website &amp; Migration", shot="lakesidethreadz.jpg",
        blurb="A custom-embroidery and DTF shop in Onalaska, TX — moved off an AI site builder onto a site they actually own.",
        brief="Lakeside&rsquo;s site lived inside an AI builder that shipped a single-page app &mdash; impossible to own, hard to change, and invisible to search. They needed the real thing.",
        work=[
            "Migrated the shop off Mocha (an AI builder that shipped a client-rendered SPA) to a static, self-owned site on Cloudflare Workers.",
            "Built a Playwright headless-Chromium snapshot pipeline to capture real, per-page HTML from the single-page app across 31 routes.",
            "Rebuilt working contact and quote forms on a Cloudflare Worker with Resend email and spam protection.",
            "Self-hosted every image and asset and shipped a branded 404, sitemap, and robots.",
        ],
        stack=["Cloudflare Workers", "Playwright", "Resend"],
    ),
    dict(
        slug="polk-county-golf-carts", name="Polk County Golf Carts", url="https://polkcountygolfcarts.com",
        cat="Website &amp; Booking Tool", tag="Website &amp; Tool", shot="polkcountygolfcarts.jpg",
        blurb="Golf-cart sales, service and custom builds in Livingston, TX — with a private rental-booking system running behind the site.",
        brief="PCGC wanted more than a brochure: a fast marketing site plus a real tool to take and manage cart rentals without paying for another SaaS.",
        work=[
            "Built a fast, self-owned static site on Cloudflare Workers, generated from shared templates.",
            "Added a customer rental-booking flow backed by Cloudflare KV, with an admin review dashboard behind auth.",
            "Wired a booking API plus Resend transactional email &mdash; a notice to the shop on every request, a thank-you to the customer on return.",
            "Generated social-share images and shipped the full SEO scaffold.",
        ],
        stack=["Cloudflare Workers", "KV", "Resend", "Python"],
    ),
    dict(
        slug="midwest-cnc", name="Midwest CNC Services", url="https://midwestcncservices.com",
        cat="Website", tag="Website", shot="midwestcnc.jpg",
        blurb="A CNC machine-repair specialist — CNC repair, spindle rebuilds, and way covers — with a clean, fast site to match the precision of the work.",
        brief="A precision CNC repair shop needed a site that read as trustworthy and technical, and loaded instantly on a phone in a machine shop.",
        work=[
            "Designed and built a fast, mobile-first marketing site for a CNC machine-repair specialist.",
            "Structured the pages around the shop&rsquo;s core work &mdash; CNC repair, spindle rebuilds, and way covers.",
            "Built and hosted on the same self-owned Cloudflare stack used across the portfolio.",
        ],
        stack=["Cloudflare", "Static HTML"],
    ),
    dict(
        slug="first-byte", name="First Byte", url="https://firstbyte.agency",
        cat="Website &amp; SEO", tag="Website &amp; SEO", shot="firstbyte.jpg",
        blurb="An award-winning digital marketing agency in The Woodlands, TX &mdash; moved off WordPress onto a fast, self-owned stack.",
        brief="First Byte&rsquo;s own site needed to be as fast and modern as the work they sell &mdash; off a heavy WordPress build and onto something they fully own.",
        work=[
            "Migrated the agency site off WordPress to a fast static build on Cloudflare Pages.",
            "Built out the Local SEO / AEO foundation to grow organic discovery.",
            "Set the structure up to scale toward their growth goals.",
        ],
        stack=["Cloudflare Pages", "Local SEO / AEO", "Static build"],
    ),
    dict(
        slug="g4-electric", name="G4 Electric", url="https://g4electric.net",
        cat="Website", tag="Website", shot="g4electric.jpg",
        blurb="A family-run electrical contractor serving Montgomery County and The Woodlands, TX.",
        brief="G4 Electric needed a clean, fast site that reads as trustworthy and local &mdash; and turns a phone search into a call.",
        work=[
            "Designed and built a mobile-first website for a family-run electrical contractor.",
            "Organized it around their services and Montgomery County service area for local search.",
            "Built for speed and easy updates.",
        ],
        stack=["Website", "Local SEO"],
    ),
    dict(
        slug="monarx", name="Monarx", url="https://monarx.com",
        cat="CMO &middot; Marketing &amp; Web", tag="SaaS &middot; where I was CMO", shot="monarx.jpg",
        role="CMO &middot; 2 years",
        blurb="An anti-malware platform for web hosts that turns malicious activity into high-converting leads &mdash; where I was CMO for two years, owning marketing and the website.",
        brief="Monarx&rsquo;s anti-malware technology detects and prevents more threats than other tools, and turns that activity into a stream of qualified leads for hosting providers. As CMO for two years, I owned go-to-market and the company&rsquo;s web presence.",
        work=[
            "Led marketing end-to-end as CMO for two years.",
            "Owned positioning and go-to-market for an anti-malware platform serving web-hosting providers.",
            "Managed the company website and brand.",
        ],
        stack=["Marketing", "Web", "Brand &amp; Growth"],
    ),
]
